---
deployment:
  tasks:
    - export PATH=/usr/local/bin:/usr/bin:/bin
    # 1. Salin file dari folder public di git ke folder public_html cPanel (kecuali folder storage untuk mencegah lock)
    - /bin/rsync -av --exclude='storage' public/ /home/eprocpej/public_html/
    
    # 2. Sesuaikan path autoload dan bootstrap di public_html/index.php secara otomatis
    - sed -i "s|__DIR__.'/../|__DIR__.'/../repositories/production-eproc/|g" /home/eprocpej/public_html/index.php
    
    # 3. Buat symlink storage dan salin folder fisik (fix 403 PDF dengan memperbaiki permission)
    - /usr/local/bin/ea-php83 artisan storage:link --force
    - /bin/rm -rf /home/eprocpej/public_html/storage
    - /bin/mkdir -p /home/eprocpej/public_html/storage
    - /bin/cp -R storage/app/public/. /home/eprocpej/public_html/storage/
    - chmod -R 755 /home/eprocpej/public_html/storage
    - find /home/eprocpej/public_html/storage -type f -exec chmod 644 {} \;

    # 4. Jalankan migrasi database
    - /usr/local/bin/ea-php83 artisan migrate --force
    
    # 5. Bersihkan cache di server
    - /usr/local/bin/ea-php83 artisan view:clear
    - /usr/local/bin/ea-php83 artisan config:clear
    - /usr/local/bin/ea-php83 artisan route:clear
